# Generated by Django 4.2.27 on 2026-01-12 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_circles', to=settings.AUTH_USER_MODEL),
        ),
    ]
