# Generated by Django 4.2.27 on 2026-01-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kvkk_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SudokuGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=list)),
                ('initial_board', models.JSONField(default=list)),
                ('solution', models.JSONField(default=list)),
                ('difficulty', models.CharField(default='easy', max_length=20)),
                ('is_solved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sudoku_game', to='core.circle')),
            ],
        ),
    ]
